services:
  api:
    build: 
      context: .
      dockerfile: ./api/Dockerfile
    container_name: financeml_api
    ports:
      - "8000:8000"
    environment:
      - PYTHONUNBUFFERED=1
      - LOG_LEVEL=INFO
      # API Keys (optional - .env dosyasından okunur)
      - ALPHA_VANTAGE_API_KEY=${ALPHA_VANTAGE_API_KEY:-demo}
      - POLYGON_API_KEY=${POLYGON_API_KEY:-}
      # Network settings
      - REQUESTS_CA_BUNDLE=/etc/ssl/certs/ca-certificates.crt
    volumes:
      # Mount parent directories so API can access data and models
      - ./data:/app/data
      - ./models:/app/models
      - ./api:/app/api
    dns:
      # Google ve Cloudflare DNS
      - 8.8.8.8
      - 1.1.1.1
    networks:
      - finance_network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: financeml_frontend
    ports:
      - "3000:80"
    depends_on:
      api:
        condition: service_healthy
    networks:
      - finance_network
    restart: unless-stopped

networks:
  finance_network:
    driver: bridge