services:
  api:
    build:
      context: .
      dockerfile: ./api/Dockerfile
    container_name: financeml_api
    ports:
      - "8000:8000"
    environment:
      - PYTHONUNBUFFERED=1
      - PYTHONPATH=/app
      - PYTHONHTTPSVERIFY=0
    volumes:
      - ./models:/app/models
      - ./data:/app/data
      - ./logs:/app/logs
    healthcheck:
      test: ["CMD-SHELL", "python -c \"import requests; requests.get('http://localhost:8000/health', verify=False)\""]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s
    restart: unless-stopped
    networks:
      - financeml_network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        - NPM_REGISTRY=https://registry.npmjs.org/
    container_name: financeml_frontend
    ports:
      - "3000:80"
    environment:
      - REACT_APP_API_URL=http://localhost:8000
    depends_on:
      - api
    restart: unless-stopped
    networks:
      - financeml_network

networks:
  financeml_network:
    driver: bridge