name: Dependency Update Check

on:
  schedule:
    # Run every Monday at 9 AM UTC
    - cron: '0 9 * * 1'
  workflow_dispatch:

jobs:
  check-dependencies:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'
    
    - name: Install pip-audit
      run: |
        python -m pip install --upgrade pip
        pip install pip-audit
    
    - name: Check for vulnerabilities in dependencies
      run: |
        pip-audit --requirement requirements.txt --format json > audit-results.json || true
    
    - name: Upload audit results
      uses: actions/upload-artifact@v4
      with:
        name: dependency-audit
        path: audit-results.json
    
    - name: Create issue if vulnerabilities found
      if: failure()
      uses: actions/github-script@v7
      with:
        script: |
          github.rest.issues.create({
            owner: context.repo.owner,
            repo: context.repo.repo,
            title: '🚨 Security vulnerabilities detected in dependencies',
            body: 'Automated scan found security vulnerabilities. Check workflow artifacts for details.',
            labels: ['security', 'dependencies']
          })
